steps:
- name: 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-db07673ae0bd/typescript/node:20.14.0-alpine'
  id: 'Install dependencies'
  entrypoint: 'npm'
  args: ['install']

- name: 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-db07673ae0bd/typescript/node:20.14.0-alpine'
  id: 'Run lint'
  waitFor:
    - 'Install dependencies'
  entrypoint: 'npm'
  args: ['run', 'lint']

- name: 'us-central1-docker.pkg.dev/qwiklabs-gcp-03-db07673ae0bd/typescript/node:20.14.0-alpine'
  id: 'Run test'
  waitFor:
    - 'Run lint'
  entrypoint: 'npm'
  args: ['test']