steps:
- name: 'node:22-alpine3.19'
  id: 'Install dependencies'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      rm -f package-lock.json
      echo "Done remove package-lock.json"
      echo "Installing dependencies"
      npm install

- name: 'node:22-alpine3.19'
  id: 'Run lint'
  waitFor:
    - 'Install dependencies'
  entrypoint: 'npm'
  args: ['run', 'lint']

- name: 'node:22-alpine3.19'
  id: 'Run test'
  waitFor:
    - 'Run lint'
  entrypoint: 'npm'
  args: ['test']