steps:
- name: 'node:22-alpine3.19'
  id: 'Install dependencies'
  entrypoint: 'npm'
  args: ['install']

- name: 'node:22-alpine3.19'
  id: 'Run lint'
  waitFor:
    - 'Install dependencies'
  entrypoint: 'npm'
  args: ['run', 'lint']

- name: 'node:22-alpine3.19'
  id: 'Run test'
  waitFor:
    - 'Run lint'
  entrypoint: 'npm'
  args: ['test']