steps:
# - name: 'node:22-alpine3.19'
#   id: 'Install dependencies'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       echo "Removing package-lock.json"
#       rm -f package-lock.json
#       echo "--------------------------"
#       echo "Installing dependencies"
#       npm install

- name: 'us-central1-docker.pkg.dev/qwiklabs-gcp-00-502aef9154d0/typescript/node:20.14.0-alpine'
  id: 'Run lint'
  # waitFor:
  #   - 'Install dependencies'
  entrypoint: 'npm'
  args: ['run', 'lint']

- name: 'us-central1-docker.pkg.dev/qwiklabs-gcp-00-502aef9154d0/typescript/node:20.14.0-alpine'
  id: 'Run test'
  waitFor:
    - 'Run lint'
  entrypoint: 'npm'
  args: ['test']