steps:
- name: 'gcr.io/cloud-builders/npm'
  id: 'Install dependencies'
  entrypoint: 'npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  id: 'Run lint'
  waitFor:
    - 'Install dependencies'
  entrypoint: 'npm'
  args: ['run', 'lint']

- name: 'gcr.io/cloud-builders/npm'
  id: 'Run test'
  waitFor:
    - 'Run lint'
  entrypoint: 'npm'
  args: ['test']